// ROOMS ACTIONS
export const GET_ALL_ROOMS = "GET_ALL_ROOMS";
export const ADD_ALL_ROOMS_TO_STATE = "ADD_ALL_ROOMS_TO_STATE";
export const GET_FOLLOWING_ROOMS = "GET_FOLLOWING_ROOMS";
export const ADD_FOLLOWING_ROOMS_TO_STATE = "ADD_FOLLOWING_ROOMS_TO_STATE";
export const MAKE_NEW_ROOM = "MAKE_NEW_ROOM";

// HOME ACTIONS
export const GET_POPULAR_ROOMS = "GET_POPULAR_ROOMS";
export const ADD_POPULAR_ROOMS_TO_STATE = "ADD_POPULAR_ROOMS_TO_STATE";

// AUTH ACTIONS
export const SIGN_IN_WITH_EMAIL = "SIGN_IN_WITH_EMAIL";
export const SIGN_UP_WITH_EMAIL = "SIGN_UP_WITH_EMAIL";
export const VERIFY_EMAIL = "VERIFY_EMAIL";
export const SET_VERIFIED_EMAIL = "SET_VERIFIED_EMAIL";
export const GET_USER_INFO = "GET_USER_INFO";
export const ADD_USER_INFO = "ADD_USER_INFO";
export const AUTH_HIDE_MESSAGE = 'AUTH_HIDE_MESSAGE';
export const AUTH_SHOW_MESSAGE = 'AUTH_SHOW_MESSAGE';
export const MAKE_SIGN_IN_VISIBLE = 'MAKE_SIGN_IN_VISIBLE';
export const MAKE_SIGN_IN_UNVISIBLE = 'MAKE_SIGN_IN_UNVISIBLE';
export const MAKE_SIGN_UP_VISIBLE = 'MAKE_SIGN_UP_VISIBLE';
export const MAKE_SIGN_UP_UNVISIBLE = 'MAKE_SIGN_UP_UNVISIBLE';


