// ROOMS ACTIONS
export const GET_ALL_ROOMS = "GET_ALL_ROOMS";
export const ADD_ALL_ROOMS_TO_STATE = "ADD_ALL_ROOMS_TO_STATE";
export const GET_FOLLOWING_ROOMS = "GET_FOLLOWING_ROOMS";
export const ADD_FOLLOWING_ROOMS_TO_STATE = "ADD_FOLLOWING_ROOMS_TO_STATE";
export const MAKE_NEW_ROOM = "MAKE_NEW_ROOM";
export const MAKE_ROOM_MAKER_VISIBLE = 'MAKE_ROOM_MAKER_VISIBLE';
export const MAKE_ROOM_MAKER_UNVISIBLE = 'MAKE_ROOM_MAKER_UNVISIBLE';

// HOME ACTIONS
export const GET_POPULAR_REVIEWS = "GET_POPULAR_REVIEWS";
export const ADD_POPULAR_REVIEWS_TO_STATE = "ADD_POPULAR_REVIEWS_TO_STATE";

// AUTH ACTIONS
export const SIGN_IN_WITH_EMAIL = "SIGN_IN_WITH_EMAIL";
export const SIGN_UP_WITH_EMAIL = "SIGN_UP_WITH_EMAIL";
export const VERIFY_EMAIL = "VERIFY_EMAIL";
export const SET_VERIFIED_EMAIL = "SET_VERIFIED_EMAIL";
export const GET_USER_INFO = "GET_USER_INFO";
export const ADD_USER_INFO = "ADD_USER_INFO";
export const SAVE_SIGN_UP_USER_INFO = "SAVE_SIGN_UP_USER_INFO";
export const MAKE_SIGN_IN_VISIBLE = 'MAKE_SIGN_IN_VISIBLE';
export const MAKE_SIGN_IN_UNVISIBLE = 'MAKE_SIGN_IN_UNVISIBLE';
export const MAKE_SIGN_UP_VISIBLE = 'MAKE_SIGN_UP_VISIBLE';
export const MAKE_SIGN_UP_UNVISIBLE = 'MAKE_SIGN_UP_UNVISIBLE';
export const GET_USER_INFO_WITH_SESSION = 'GET_USER_INFO_WITH_SESSION';
export const DETECT_NO_SESSION = 'DETECT_NO_SESSION';
export const SIGN_OUT = 'SIGN_OUT';
export const REMOVE_USER_INFO = 'REMOVE_USER_INFO';

// MESSAGE ACTIONS
export const HIDE_MESSAGE = 'HIDE_MESSAGE';
export const SHOW_MESSAGE = 'SHOW_MESSAGE';

// ROUTER ACTIONS
export const SET_UP_TARGET_PATH = 'SET_UP_TARGET_PATH';
export const SET_UP_CURRENT_PATH = 'SET_UP_CURRENT_PATH';
