// ROOMS ACTIONS
export const GET_ALL_ROOMS = "GET_ALL_ROOMS";
export const ADD_ALL_ROOMS_TO_STATE = "ADD_ALL_ROOMS_TO_STATE";
export const GET_FOLLOWING_ROOMS = "GET_FOLLOWING_ROOMS";
export const ADD_FOLLOWING_ROOMS_TO_STATE = "ADD_FOLLOWING_ROOMS_TO_STATE";
export const MAKE_NEW_ROOM = "MAKE_NEW_ROOM";

// HOME ACTIONS
export const GET_POPULAR_ROOMS = "GET_POPULAR_ROOMS";
export const ADD_POPULAR_ROOMS_TO_STATE = "ADD_POPULAR_ROOMS_TO_STATE";
